---
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: 'choco install rust-ms'
  displayName: 'Install Rust toolchain'
- script: 'cargo check'
  displayName: 'Check for errors'
- script: 'cargo build --release'
  displayName: 'Build in release mode'
