---
version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run: choco install rust-ms
      - checkout
      - run: cargo check
      - run: cargo build --release
